<?php
?>
<script type="text/javascript">
/* inject:js */

(function(){var e=this,t=e.__szzz;function o(e,t=!1){return e?window===this?new o(e,t):(this.node="string"==typeof e?t?t.querySelectorAll(e):document.querySelectorAll(e):void 0===e.length?[e]:e,this):window===this?new o(e):this}e.__szzz=o,o.noConflict=function(){return e.__szzz=t,this},o.prototype={removeClass:function(){for(var e=0;e<this.node.length;e++)for(var t=0;t<arguments.length;t++)this.node[e].classList.remove(arguments[t]);return this},addClass:function(){for(var e=0;e<this.node.length;e++)for(var t=0;t<arguments.length;t++)this.node[e].classList.add(arguments[t]);return this},whenInViewbox:function(e=!1){if("IntersectionObserver"in window){let o={root:null,rootMargin:"500px",threshold:0};var t;if(arguments[1]&&"object"==typeof arguments[1])for(t in arguments[1])o.hasOwnProperty(t)&&(o[t]=arguments[1][t]);let r=new IntersectionObserver((t,o)=>{t.forEach(t=>{t.intersectionRatio>0&&e&&e instanceof Function&&(e(t.target),o.unobserve(t.target))})},o);for(i=0;i<this.node.length;i++)r.observe(this.node[i])}else e&&e instanceof Function&&this.node.forEach(t=>e(t));return this},importModule:function(e=null,t="script"){if(""!==e&&null!=e)return"stylesheet"!=t&&"css"!=t&&"style"!=t||(tagName="link",sourceAttrName="href",rel="stylesheet",t="text/css"),"js"!=t&&"script"!=t||(tagName="script",sourceAttrName="src",rel="",t="text/javascript"),new Promise(o=>{node=document.createElement(tagName),node.setAttribute(sourceAttrName,e),node.setAttribute("rel",rel),node.setAttribute("type",t),document.getElementsByTagName("head")[0].appendChild(node),node.onload=function(){o(!0)}});console.error("ImportModule expects a link to the module.")}}}).call(this);const dope=()=>{"complete"!=document.readyState&&setTimeout(dope,1),document.readyState};window.addEventListener("load",()=>{console.log("on = "+document.readyState);const e=window.szzzLazifyData,t=e.styles,o=e.scripts;var r={styles:[],scripts:[]},n=(e="",t="")=>(identifier=t.replace(/\.|\#|\s|\,|\+|\*|\~|\=|\>|\[|\]/g,"_"),identifier="szzzLazy_style_"+identifier,{observed:e,selector:t,identifier:identifier});t.forEach((e,t)=>{void 0!==e.DOM_selector?(obSelector=void 0!==e.observed_selector?e.observed_selector:e.DOM_selector,r.styles.push(n(obSelector,e.DOM_selector)),__szzz(obSelector).whenInViewbox(t=>{r.styles.forEach(e=>{t.matches(e.observed)&&($a=document.getElementById(e.identifier),null!=$a&&$a.parentElement.removeChild($a))}),__szzz().importModule(e.source,"style").then(e=>{})})):__szzz().importModule(e.source,"style").then(e=>{})}),o.forEach((e,t)=>{void 0!==e.DOM_selector?(obSelector=void 0!==e.observed_selector?e.observed_selector:e.DOM_selector,r.scripts.push(n(obSelector,e.DOM_selector)),__szzz(obSelector).whenInViewbox(t=>{r.scripts.forEach(e=>{t.matches(e.observed)&&($a=document.getElementById(e.identifier),null!=$a&&$a.parentElement.removeChild($a))}),__szzz().importModule(e.source,"script").then(e=>{})})):__szzz().importModule(e.source,"script").then(e=>{})})});

/* endinject */
</script>
